NJWE-1443 - Update Notifier new field
newjersey/d4ad pull request #1950
Opened 2024-01-24 21:29 UTC by scwambach

2024-01-25 12:54 UTC, mflymfly reviewed
@scwambach  - When I pull up this PR locally I am not able to see this feature at all. I very well might be doing something wrong though.

^ This issue has been resolved

2024-01-25 17:04 UTC, mflymfly requested changes
This is looking really really good. I just have a couple, hopefully small things.

- Add "Other" as final option in dropdown list
- When the dropdown is open and you click anywhere outside of it, the dropdown should close
- On **mobile**, when the dropdown is open, there is no scroll bar indicator like there is on desktop. Can we add that in?

**This one may be a larger lift**
- I think the error warnings happen a little too easily and that may be due to the mockups I provided, I'd like to work through that logic but might be best to do that on a quick call. But essentially I think it should work as such:

Email error prompts 

- when form is submitted without the email field filled in at all or an invalid email is entered
- when an invalid email is entered and then user changes focus

Which best describes you error prompts

- when form is submitted without a selection being made

Just changing focus should not cause an error message alone. Sorry if this is confusing or a large lift. Definitely happy to chat this through.

2024-01-29 16:06 UTC, scwambach commented
@mflymfly I changed the error function that checks if the email is valid to only fire when there's a value in the field so that it's not annoying when tabbing through

2024-01-29 16:49 UTC, mflymfly approved these changes

2024-01-29 17:46 UTC, merged