Global header footer
newjersey/d4ad pull request #912
Opened 2023-03-31 21:35 UTC by scwambach

Built the global header and footer with the New Jersey component styles. Made updates to the Training Explorer nav

2023-04-04 14:26 UTC, scwambach commented on frontend/src/components/Layout.tsx
> +
These all have to be separate queries because the request would be too large from contentful otherwise.

2023-04-06 16:24 UTC, ChelseaKR requested changes
Please fix implementation failing accessibility tests raised by Cypress

2023-04-06 19:52 UTC, scwambach commented
> Please fix implementation failing accessibility tests raised by Cypress

Should be fixed now!

2023-04-07 20:18 UTC, ChelseaKR approved these changes

2023-04-11 15:47 UTC, merged